// AUTO-GENERATED by scripts/generate-guides-index.mjs - do not hand-edit.
// Re-run that script after adding or removing any data/guides/<slug>.ts file, or any
// app/(site)/guide/<slug>/page.tsx literal route directory.
import type { GuideProduct, HowToChooseSection } from "@/components/guide/RichGuidePage";

export interface GuideDataModule {
  guideTitle: string;
  metaTitle: string;
  metaDescription: string;
  mainKeyword?: string;
  introParagraphs?: string[];
  lastUpdated: string;
  readTime: string;
  heroImage: string;
  heroImageAlt?: string;
  products: GuideProduct[];
  howWeEvaluated?: { title: string; description: string }[];
  howToChoose?: HowToChooseSection[];
  buyingCriteria?: { criterion: string; explanation: string }[];
  faq?: { q: string; a: string }[];
  relatedGuides?: { href: string; title: string }[];
}

export const guideDataLoaders: Record<string, () => Promise<GuideDataModule>> = {
  "best-12v-car-coffee-warmers": () => import("./guides/best-12v-car-coffee-warmers"),
  "best-camping-chairs": () => import("./guides/best-camping-chairs"),
  "best-camping-chairs-400-lb-capacity": () => import("./guides/best-camping-chairs-400-lb-capacity"),
  "best-camping-chairs-600-lb-capacity": () => import("./guides/best-camping-chairs-600-lb-capacity"),
  "best-camping-chairs-with-lumbar-support": () => import("./guides/best-camping-chairs-with-lumbar-support"),
  "best-extra-wide-zero-gravity-chair": () => import("./guides/best-extra-wide-zero-gravity-chair"),
  "best-hammock-camping-chairs": () => import("./guides/best-hammock-camping-chairs"),
  "best-mesh-camping-chairs": () => import("./guides/best-mesh-camping-chairs"),
  "best-mini-portable-generator-for-camping": () => import("./guides/best-mini-portable-generator-for-camping"),
  "best-padded-camping-chairs": () => import("./guides/best-padded-camping-chairs"),
  "best-portable-generator-for-camping": () => import("./guides/best-portable-generator-for-camping"),
  "best-portable-generator-for-camping-picks": () => import("./guides/best-portable-generator-for-camping-picks"),
  "best-portable-generator-quiet-box-for-camping": () => import("./guides/best-portable-generator-quiet-box-for-camping"),
  "best-portable-power-station-for-camping": () => import("./guides/best-portable-power-station-for-camping"),
  "best-portable-power-station-for-cpap-camping": () => import("./guides/best-portable-power-station-for-cpap-camping"),
  "best-portable-power-stations-for-camping": () => import("./guides/best-portable-power-stations-for-camping"),
  "best-portable-quiet-generator-for-camping": () => import("./guides/best-portable-quiet-generator-for-camping"),
  "best-portable-solar-generator-for-camping": () => import("./guides/best-portable-solar-generator-for-camping"),
  "best-power-banks-for-camping": () => import("./guides/best-power-banks-for-camping"),
  "best-projectors-for-camping": () => import("./guides/best-projectors-for-camping"),
  "best-quiet-generators-for-camping": () => import("./guides/best-quiet-generators-for-camping"),
  "best-quiet-portable-generator-for-camping": () => import("./guides/best-quiet-portable-generator-for-camping"),
  "best-quietest-portable-generator-for-camping": () => import("./guides/best-quietest-portable-generator-for-camping"),
  "best-small-portable-generator-for-camping": () => import("./guides/best-small-portable-generator-for-camping"),
  "best-solar-generator-for-camping": () => import("./guides/best-solar-generator-for-camping"),
  "best-solar-generator-kit-for-camping": () => import("./guides/best-solar-generator-kit-for-camping"),
  "best-solar-generators-for-camping": () => import("./guides/best-solar-generators-for-camping"),
  "best-solar-quiet-generator-for-camping": () => import("./guides/best-solar-quiet-generator-for-camping"),
  "best-swivel-camping-chairs": () => import("./guides/best-swivel-camping-chairs"),
  "best-tripod-camping-stools": () => import("./guides/best-tripod-camping-stools"),
  "best-zero-gravity-chair-for-camping": () => import("./guides/best-zero-gravity-chair-for-camping"),
  "best-zero-gravity-chair-with-locking-mechanism": () => import("./guides/best-zero-gravity-chair-with-locking-mechanism"),
  "best-zero-gravity-chair-with-lumbar-support": () => import("./guides/best-zero-gravity-chair-with-lumbar-support"),
};

// Slugs whose full content only exists in a hand-authored app/(site)/guide/<slug>/
// page.tsx route (not covered by guideDataLoaders above). A silo detail page must
// redirect back to /guide/<slug> for these rather than render GuideDetail's thin
// registry stub, or it silently serves an emptied-out page.
export const legacyLiteralRouteSlugs: string[] = [
  "all",
];
